name: tutorial_mosdef
channels:
  - conda-forge
  - conda-forge/label/hoomd_dev
  - bioconda
dependencies:
  - hoomd
  - constrainmol
  - ele
  - flowermd
  - foyer
  - fresnel
  - freud
  - gmso>=0.11.1
  - gromacs
  - gsd
  - h5py
  - jupyter
  - jinja2
  - ipympl>=0.9.3
  - lammps
  - matplotlib
  - mbuild
  - mdtraj
  - mosdef_cassandra
  - numpy
  - nglview
  - openmm>=7.6
  - packmol>=18
  - pandas
  - panedr
  - parmed>=3.4.3
  - pymbar
  - pytest
  - rdkit
  - scipy=1.9.0
  - seaborn
  - signac=2.0.0
  - signac-dashboard
  - signac-flow=0.25.1
  - unyt
  - py3dmol
